# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: tag

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.13.4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - run: pnpm i --frozen-lockfile
      - run: pnpm build
      - run: ls *.md
      - run: pnpm changelog
      - run: pnpm changelogFull
      - name: get tag
        run: |
          if [[ $GITHUB_REF_NAME =~ ^v.+ ]]; then
            pkgName="main"
          else
            # `%@*` truncates @ and version number from the right side.
            # https://stackoverflow.com/questions/9532654/expression-after-last-specific-character
            pkgName=${GITHUB_REF_NAME%@*}
          fi

          echo $pkgName
          echo "pkgName=$pkgName" >> $GITHUB_ENV
          ls *.md
          echo "temp:"
          cat tempCHANGELOG.md
          echo "full:"
          cat FullCHANGELOG.md
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo ${{steps.build_changelog.outputs}}
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/index.js"
          body: ${{steps.build_changelog.outputs.changelog}}
          # bodyFile: "tempCHANGELOG.md"
        # uses: softprops/action-gh-release@v1
        # with:
        #   files: dist/index.js
        #   body_path: tempCHANGELOG.md
          # body: |
          #   Please refer to [CHANGELOG.md](https://github.com/ilyydy/ci-test/blob/${{ github.ref_name }}/packages/${{ env.pkgName }}/CHANGELOG.md) for details.
