# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: tag

on:
  push:
    tags:
      - "*@*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: get tag
        run: |
          if [[ $GITHUB_REF_NAME =~ ^v.+ ]]; then
            pkgName="main"
          else
            # `%@*` truncates @ and version number from the right side.
            # https://stackoverflow.com/questions/9532654/expression-after-last-specific-character
            pkgName=${GITHUB_REF_NAME%@*}
          fi

          echo $pkgName
          echo "pkgName=$pkgName" >> $GITHUB_ENV
          # echo '${{ toJSON(github) }}'
          pnpm conventional-changelog
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/index.js
          body: |
            Please refer to [CHANGELOG.md](https://github.com/ilyydy/ci-test/blob/${{ github.ref_name }}/packages/${{ env.pkgName }}/CHANGELOG.md) for details.
